CREATE DATABASE Exercicio1_2;

USE Exercicio1_2;

CREATE TABLE Marcas(

	MarcaID INT PRIMARY KEY IDENTITY,
	NomeMarca VARCHAR(30) NOT NULL

)

CREATE TABLE Modelos(

	ModeloID INT PRIMARY KEY IDENTITY,
	NomeModelo VARCHAR(30) NOT NULL

)

CREATE TABLE Veiculos(

	VeiculoID INT PRIMARY KEY IDENTITY,
	Placa VARCHAR(7) NOT NULL,
	MarcaID INT FOREIGN KEY REFERENCES Marcas(MarcaID) NOT NULL,
	ModeloID INT FOREIGN KEY REFERENCES Modelos(ModeloID) NOT NULL

)

CREATE TABLE Clientes(

	ClienteID INT PRIMARY KEY IDENTITY,
	ClienteNome VARCHAR(50) NOT NULL,
	CPF INT NOT NULL
	
)

CREATE TABLE Alugueis(

	ClienteID INT FOREIGN KEY REFERENCES Clientes(ClienteID) NOT NULL,
	VeiculoID INT FOREIGN KEY REFERENCES Veiculos(VeiculoID) NOT NULL,
	DataRetirada DATE NOT NULL,
	DataDevolucao DATE NOT NULL,
	PrecoAluguel INT NOT NULL

)