CREATE DATABASE Exercicio1_3

USE Exercicio1_3

CREATE TABLE Clinica(

	IDClinica INT PRIMARY KEY IDENTITY,
	NomeClinica VARCHAR(30) NOT NULL,
	EnderecoClinica VARCHAR(100) NOT NULL

)

CREATE TABLE Veterinario(
	IDVeterinario INT PRIMARY KEY IDENTITY,
	IDClinica INT FOREIGN KEY REFERENCES Clinica(IDClinica) NOT NULL,
	NomeVeterinario VARCHAR(30) NOT NULL,
	CRMV VARCHAR(5) NOT NULL
)

CREATE TABLE TiposPet(
	IDTipo INT PRIMARY KEY IDENTITY,
	NomeTipo VARCHAR(30)
)

CREATE TABLE RacasPet(
	IDRaca INT PRIMARY KEY IDENTITY,
	NomeRaca VARCHAR(30)

)

CREATE TABLE Dono(
	IDDono INT PRIMARY KEY IDENTITY,
	Endereco VARCHAR(50) NOT NULL

)

CREATE TABLE Pets(
	IDPet INT PRIMARY KEY IDENTITY ,
	IDRaca INT FOREIGN KEY REFERENCES RacasPet(IDRaca) NOT NULL,
	IDTipo INT FOREIGN KEY REFERENCES TiposPet(IDTipo) NOT NULL,
	IDDono INT FOREIGN KEY REFERENCES Dono(IDDono) NOT NULL,
	NomePet VARCHAR(30) NOT NULL,
	DataNascimento DATE NOT NULL
)

CREATE TABLE Atendimento(
	IDAtendimento INT PRIMARY KEY IDENTITY,
	IDVeterinario INT FOREIGN KEY REFERENCES Veterinario(IDVeterinario) NOT NULL,
	IDPet INT FOREIGN KEY REFERENCES Pets(IDPet) NOT NULL
)


